### ISSUE TITLE
Support of redirects

### ISSUE THREAD

**Issue by eMerzh** [zupzup/static-aws-deploy#1]
Hi,

thanks for the project, it looks really great for a static website ..
i was playing a bit with it but noticed that it does not support redirects.

it could be really cool too support them as s3_website does :)
(https://github.com/laurilehmijoki/s3_website#configuring-redirects-on-your-s3-website)

thanks

**Comment by zupzup** [comment]
Hi,

Thanks for the feedback.

Redirects look useful, thank you for the tip. They should also be fairly straightforward to implement. I will look into it.

**Comment by zupzup** [comment]
After reading http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html I believe this is already possible right now.

To create a redirect, you simply need to add a metadata configuration, e.g.: if you wanted to create a redirect from `page_1.html` to `page_2.html`, you could simply upload a zero-byte file with name `page_1.html` and add the following configuration:

```
    metadata:
        - regex: 'page_1\.html'
          headers:
              - 'x-amz-website-redirect-location': '/page_2.html'
```
